import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:stocksnap/models/item.dart';
import 'package:stocksnap/screens/drill_down_screen.dart';
import 'package:stocksnap/services/database_service.dart';
import 'package:stocksnap/services/inventory_notifier.dart';
import 'package:stocksnap/services/prefs_service.dart';
import 'package:stocksnap/services/purchase_service.dart';
import 'package:stocksnap/services/stocksnap_tab_notifier.dart';
import 'package:stocksnap/widgets/pro_upgrade_sheet.dart';

class DashboardScreen extends StatefulWidget {
  const DashboardScreen({super.key});

  @override
  State<DashboardScreen> createState() => _DashboardScreenState();
}

class _DashboardScreenState extends State<DashboardScreen> {
  bool _loading = true;
  List<Item> _items = [];
  List<Item> _lowStock = [];
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    PurchaseService.instance.addListener(_onProChanged);
    inventoryChangeNotifier.addListener(_onInventoryChanged);
    _loadData();
  }

  @override
  void dispose() {
    PurchaseService.instance.removeListener(_onProChanged);
    inventoryChangeNotifier.removeListener(_onInventoryChanged);
    super.dispose();
  }

  void _onProChanged() => setState(() {});

  void _onInventoryChanged() => _loadData();

  Future<void> _loadData() async {
    setState(() => _loading = true);
    try {
      final items = await DatabaseService.instance.getAllItems();
      final lowStock = await DatabaseService.instance.getLowStockItems();
      if (!mounted) return;
      setState(() {
        _items = items;
        _lowStock = lowStock;
        _errorMessage = null;
      });
    } catch (_) {
      if (!mounted) return;
      setState(() => _errorMessage = 'Unable to load dashboard.');
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  Future<void> _exportPDF() async {
    final currencySymbol = PrefsService.instance.currency;
    final dateFormat = DateFormat('MMM d, yyyy');
    final uniqueItems = _items.fold<List<Item>>([], (list, item) {
      if (!list.any((e) => e.id == item.id)) list.add(item);
      return list;
    });
    final totalItems = _items.length;
    final totalValue = _items.fold<double>(0, (sum, item) => sum + item.totalValue);
    final totalRevenue = _items.fold<double>(0, (sum, item) => sum + item.totalRevenue);
    final totalProfit = totalRevenue - totalValue;
    final lowStock = uniqueItems.where((item) => item.isLowStock).toList();

    final pdf = pw.Document();
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        footer: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 8),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by StockSnap',
                style: pw.TextStyle(
                  fontSize: 8,
                  color: PdfColors.grey500,
                ),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(
                  fontSize: 8,
                  color: PdfColors.grey500,
                ),
              ),
            ],
          ),
        ),
        build: (context) => [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'StockSnap',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                dateFormat.format(DateTime.now()),
                style: const pw.TextStyle(
                  fontSize: 11,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 24),
          pw.Divider(color: PdfColors.grey300, thickness: 0.5),
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'SUMMARY',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey600,
                    letterSpacing: 1.2,
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    _summaryItem('Total Items', '$totalItems'),
                    _summaryItem(
                      'Inventory Value',
                      '$currencySymbol${totalValue.toStringAsFixed(2)}',
                    ),
                    _summaryItem(
                      'Potential Revenue',
                      '$currencySymbol${totalRevenue.toStringAsFixed(2)}',
                    ),
                    _summaryItem(
                      'Potential Profit',
                      '$currencySymbol${totalProfit.toStringAsFixed(2)}',
                    ),
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.Divider(color: PdfColors.grey300, thickness: 0.5),
          pw.SizedBox(height: 20),
          pw.Text(
            'INVENTORY',
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey600,
              letterSpacing: 1.2,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Table(
            border: pw.TableBorder(
              bottom: const pw.BorderSide(color: PdfColors.grey300),
              horizontalInside: const pw.BorderSide(color: PdfColors.grey200),
            ),
            columnWidths: {
              0: const pw.FlexColumnWidth(2.5),
              1: const pw.FlexColumnWidth(1.0),
              2: const pw.FlexColumnWidth(1.0),
              3: const pw.FlexColumnWidth(1.2),
              4: const pw.FlexColumnWidth(0.5),
              5: const pw.FlexColumnWidth(0.8),
              6: const pw.FlexColumnWidth(0.8),
              7: const pw.FlexColumnWidth(0.7),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                children: ['Name', 'SKU', 'Barcode', 'Category', 'Qty', 'Cost', 'Sell', 'Margin']
                    .map(
                      (h) => pw.Padding(
                        padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                        child: pw.Text(
                          h,
                          style: pw.TextStyle(
                            fontWeight: pw.FontWeight.bold,
                            fontSize: 8,
                            color: PdfColors.grey700,
                          ),
                        ),
                      ),
                    )
                    .toList(),
              ),
              ...uniqueItems.map(
                (item) => pw.TableRow(
                  children: [
                    _cell(item.name),
                    _cell(item.sku ?? '-'),
                    _cell(item.barcode ?? '-'),
                    _cell(item.category ?? '-'),
                    _cell('${item.quantity}'),
                    _cell('$currencySymbol${item.costPrice.toStringAsFixed(2)}'),
                    _cell('$currencySymbol${item.sellPrice.toStringAsFixed(2)}'),
                    _cell(
                      item.sellPrice > 0
                          ? '${((item.sellPrice - item.costPrice) / item.sellPrice * 100).toStringAsFixed(1)}%'
                          : '-',
                    ),
                  ],
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Divider(color: PdfColors.grey300, thickness: 0.5),
          pw.SizedBox(height: 20),
          pw.Text(
            'LOW STOCK',
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey600,
              letterSpacing: 1.2,
            ),
          ),
          pw.SizedBox(height: 8),
          if (lowStock.isEmpty)
            pw.Text(
              'All stocked up',
              style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
            )
          else
            ...lowStock.map(
              (i) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 4),
                child: pw.Text(
                  '- ${i.name}  |  Qty: ${i.quantity}  (Min: ${i.minQuantity})',
                  style: pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.red700,
                  ),
                ),
              ),
            ),
        ],
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'stocksnap_inventory_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }

  @override
  Widget build(BuildContext context) {
    final currencySymbol = PrefsService.instance.currency;
    final totalItems = _items.length;
    final totalValue = _items.fold<double>(0, (sum, item) => sum + item.totalValue);
    final totalRevenue = _items.fold<double>(0, (sum, item) => sum + item.totalRevenue);
    final totalProfit = totalRevenue - totalValue;
    final marginItems = _items.where((i) => i.sellPrice > 0).toList();
    final avgMargin = marginItems.isEmpty
        ? 0.0
        : marginItems
                .map((i) => (i.sellPrice - i.costPrice) / i.sellPrice * 100)
                .reduce((a, b) => a + b) /
            marginItems.length;
    final bestItem = marginItems.isEmpty
        ? null
        : marginItems.reduce(
            (a, b) =>
                ((a.sellPrice - a.costPrice) / a.sellPrice) >
                        ((b.sellPrice - b.costPrice) / b.sellPrice)
                    ? a
                    : b,
          );
    final bestMargin = bestItem == null
        ? 0.0
        : (bestItem.sellPrice - bestItem.costPrice) / bestItem.sellPrice * 100;
    final worstItem = marginItems.isEmpty
        ? null
        : marginItems.reduce(
            (a, b) =>
                ((a.sellPrice - a.costPrice) / a.sellPrice) <
                        ((b.sellPrice - b.costPrice) / b.sellPrice)
                    ? a
                    : b,
          );
    final worstMargin = worstItem == null
        ? 0.0
        : (worstItem.sellPrice - worstItem.costPrice) /
            worstItem.sellPrice *
            100;

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text(
          'Dashboard',
          style: TextStyle(
            fontSize: 28,
            fontWeight: FontWeight.w700,
            letterSpacing: -0.5,
          ),
        ),
        titleSpacing: 20,
        elevation: 0,
        backgroundColor: Colors.white,
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 16),
            child: GestureDetector(
              onTap: () async {
                if (!PurchaseService.instance.isPro) {
                  await showStocksnapProUpgradeSheet(context);
                  return;
                }
                await _exportPDF();
              },
              child: const Text(
                'Export PDF',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                  color: Color(0xFF1A1A1A),
                ),
              ),
            ),
          ),
        ],
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : RefreshIndicator(
              onRefresh: _loadData,
              child: _errorMessage != null
                  ? ListView(
                      physics: const AlwaysScrollableScrollPhysics(),
                      padding: const EdgeInsets.all(16),
                      children: [
                        _stateCard(
                          icon: Icons.error_outline,
                          title: 'Something went wrong',
                          message: _errorMessage!,
                        ),
                      ],
                    )
                  : ListView(
                      physics: const AlwaysScrollableScrollPhysics(),
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 120),
                      children: [
                        GridView.count(
                          crossAxisCount: 2,
                          shrinkWrap: true,
                          crossAxisSpacing: 12,
                          mainAxisSpacing: 12,
                          childAspectRatio: 1.3,
                          physics: const NeverScrollableScrollPhysics(),
                          children: [
                            _summaryCard(
                              label: 'TOTAL ITEMS',
                              value: totalItems.toString(),
                              subtext: 'Items Tracked',
                              onTap: () {
                                stocksnapTabNotifier.value = 0;
                              },
                            ),
                            _summaryCard(
                              label: 'INVENTORY VALUE',
                              value: '$currencySymbol${totalValue.toStringAsFixed(2)}',
                              subtext: 'Cost Basis',
                              onTap: () {
                                final sorted = [..._items]..sort(
                                      (a, b) => (b.costPrice * b.quantity)
                                          .compareTo(a.costPrice * a.quantity),
                                    );
                                Navigator.of(context).push<void>(
                                  MaterialPageRoute(
                                    builder: (_) => DrillDownScreen(
                                      title: 'Inventory Value',
                                      items: sorted
                                          .map(
                                            (i) => DrillDownItem(
                                              name: i.name,
                                              subtitle:
                                                  i.category ?? i.sku ?? '-',
                                              primaryValue:
                                                  '$currencySymbol${(i.costPrice * i.quantity).toStringAsFixed(2)}',
                                              secondaryValue:
                                                  '${i.quantity} × $currencySymbol${i.costPrice.toStringAsFixed(2)}',
                                            ),
                                          )
                                          .toList(),
                                    ),
                                  ),
                                );
                              },
                            ),
                            _summaryCard(
                              label: 'POTENTIAL REVENUE',
                              value: '$currencySymbol${totalRevenue.toStringAsFixed(2)}',
                              subtext: 'Sell Value',
                              onTap: () {
                                final sorted = [..._items]..sort(
                                      (a, b) => (b.sellPrice * b.quantity)
                                          .compareTo(a.sellPrice * a.quantity),
                                    );
                                Navigator.of(context).push<void>(
                                  MaterialPageRoute(
                                    builder: (_) => DrillDownScreen(
                                      title: 'Potential Revenue',
                                      items: sorted
                                          .map(
                                            (i) => DrillDownItem(
                                              name: i.name,
                                              subtitle:
                                                  i.category ?? i.sku ?? '-',
                                              primaryValue:
                                                  '$currencySymbol${(i.sellPrice * i.quantity).toStringAsFixed(2)}',
                                              secondaryValue:
                                                  '${i.quantity} × $currencySymbol${i.sellPrice.toStringAsFixed(2)}',
                                            ),
                                          )
                                          .toList(),
                                    ),
                                  ),
                                );
                              },
                            ),
                            _summaryCard(
                              label: 'POTENTIAL PROFIT',
                              value: '$currencySymbol${totalProfit.toStringAsFixed(2)}',
                              subtext: 'Potential Profit',
                              onTap: () {
                                final sorted = [..._items]..sort(
                                      (a, b) =>
                                          ((b.sellPrice - b.costPrice) *
                                                  b.quantity)
                                              .compareTo(
                                            (a.sellPrice - a.costPrice) *
                                                a.quantity,
                                          ),
                                    );
                                Navigator.of(context).push<void>(
                                  MaterialPageRoute(
                                    builder: (_) => DrillDownScreen(
                                      title: 'Potential Profit',
                                      items: sorted
                                          .map(
                                            (i) => DrillDownItem(
                                              name: i.name,
                                              subtitle:
                                                  i.category ?? i.sku ?? '-',
                                              primaryValue:
                                                  '$currencySymbol${((i.sellPrice - i.costPrice) * i.quantity).toStringAsFixed(2)}',
                                              secondaryValue:
                                                  'margin ${i.sellPrice > 0 ? ((i.sellPrice - i.costPrice) / i.sellPrice * 100).toStringAsFixed(1) : "0.0"}%',
                                            ),
                                          )
                                          .toList(),
                                    ),
                                  ),
                                );
                              },
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),
                        Container(
                          width: double.infinity,
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                            color: Colors.white,
                            borderRadius: BorderRadius.circular(16),
                            border: Border.all(color: const Color(0xFFE4E6EA)),
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text(
                                'LOW STOCK',
                                style: TextStyle(
                                  fontSize: 11,
                                  fontWeight: FontWeight.w600,
                                  color: Color(0xFF8A8A8A),
                                  letterSpacing: 1.2,
                                ),
                              ),
                              const SizedBox(height: 8),
                              if (_lowStock.isEmpty) ...[
                                const Text(
                                  '0',
                                  style: TextStyle(
                                    fontSize: 28,
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                                const SizedBox(height: 4),
                                const Text(
                                  'All Items Stocked',
                                  style: TextStyle(
                                    fontSize: 12,
                                    color: Color(0xFF8A8A8A),
                                  ),
                                ),
                              ] else ...[
                                Text(
                                  '${_lowStock.length}',
                                  style: const TextStyle(
                                    fontSize: 28,
                                    fontWeight: FontWeight.w700,
                                    color: Color(0xFFFF4757),
                                  ),
                                ),
                                const SizedBox(height: 4),
                                const Text(
                                  'Items Need Restocking',
                                  style: TextStyle(
                                    fontSize: 12,
                                    color: Color(0xFF8A8A8A),
                                  ),
                                ),
                                const SizedBox(height: 12),
                                ..._lowStock.map(
                                  (item) => Padding(
                                    padding: const EdgeInsets.only(bottom: 8),
                                    child: Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.spaceBetween,
                                      children: [
                                        Expanded(
                                          child: Text(
                                            item.name,
                                            style: const TextStyle(
                                              fontSize: 14,
                                              fontWeight: FontWeight.w500,
                                            ),
                                            overflow: TextOverflow.ellipsis,
                                          ),
                                        ),
                                        Container(
                                          padding: const EdgeInsets.symmetric(
                                            horizontal: 8,
                                            vertical: 3,
                                          ),
                                          decoration: BoxDecoration(
                                            color: const Color(0xFFFFEEEE),
                                            borderRadius:
                                                BorderRadius.circular(6),
                                          ),
                                          child: Text(
                                            '${item.quantity} left',
                                            style: const TextStyle(
                                              fontSize: 12,
                                              fontWeight: FontWeight.w600,
                                              color: Color(0xFFFF4757),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ],
                            ],
                          ),
                        ),
                        const SizedBox(height: 12),
                        if (PurchaseService.instance.isPro)
                          GestureDetector(
                            onTap: () {
                              final sorted = [
                                ..._items.where((i) => i.sellPrice > 0),
                              ]..sort(
                                  (a, b) =>
                                      ((b.sellPrice - b.costPrice) /
                                              b.sellPrice)
                                          .compareTo(
                                        (a.sellPrice - a.costPrice) /
                                            a.sellPrice,
                                      ),
                                );
                              Navigator.of(context).push<void>(
                                MaterialPageRoute(
                                  builder: (_) => DrillDownScreen(
                                    title: 'Margin Insights',
                                    items: sorted
                                        .map(
                                          (i) => DrillDownItem(
                                            name: i.name,
                                            subtitle:
                                                i.category ?? i.sku ?? '-',
                                            primaryValue:
                                                '${((i.sellPrice - i.costPrice) / i.sellPrice * 100).toStringAsFixed(1)}%',
                                            secondaryValue:
                                                '$currencySymbol${(i.sellPrice - i.costPrice).toStringAsFixed(2)} per unit',
                                          ),
                                        )
                                        .toList(),
                                  ),
                                ),
                              );
                            },
                            behavior: HitTestBehavior.opaque,
                            child: Container(
                              width: double.infinity,
                              padding: const EdgeInsets.all(16),
                              decoration: BoxDecoration(
                                color: Colors.white,
                                borderRadius: BorderRadius.circular(16),
                                border: Border.all(
                                  color: const Color(0xFFE4E6EA),
                                ),
                              ),
                              child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Text(
                                  'MARGIN INSIGHTS',
                                  style: TextStyle(
                                    fontSize: 11,
                                    fontWeight: FontWeight.w600,
                                    color: Color(0xFF8A8A8A),
                                    letterSpacing: 1.2,
                                  ),
                                ),
                                const SizedBox(height: 12),
                                Text(
                                  '${avgMargin.toStringAsFixed(1)}%',
                                  style: const TextStyle(
                                    fontSize: 28,
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                                const SizedBox(height: 4),
                                const Text(
                                  'Avg Margin Across All Items',
                                  style: TextStyle(
                                    fontSize: 12,
                                    color: Color(0xFF8A8A8A),
                                  ),
                                ),
                                const SizedBox(height: 8),
                                Row(
                                  children: [
                                    Expanded(
                                      child: Row(
                                        children: [
                                          const Text(
                                            'Best item',
                                            style: TextStyle(
                                              fontSize: 13,
                                              color: Color(0xFF8A8A8A),
                                            ),
                                          ),
                                          const SizedBox(width: 4),
                                          Expanded(
                                            child: Text(
                                              bestItem?.name ?? '—',
                                              style: const TextStyle(
                                                fontSize: 13,
                                                fontWeight: FontWeight.w500,
                                                color: Color(0xFF1A1A1A),
                                              ),
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Text(
                                      '${bestMargin.toStringAsFixed(1)}%',
                                      style: const TextStyle(
                                        fontSize: 13,
                                        fontWeight: FontWeight.w600,
                                        color: Color(0xFF00C48C),
                                      ),
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 4),
                                Row(
                                  children: [
                                    Expanded(
                                      child: Row(
                                        children: [
                                          const Text(
                                            'Worst item',
                                            style: TextStyle(
                                              fontSize: 13,
                                              color: Color(0xFF8A8A8A),
                                            ),
                                          ),
                                          const SizedBox(width: 4),
                                          Expanded(
                                            child: Text(
                                              worstItem?.name ?? '—',
                                              style: const TextStyle(
                                                fontSize: 13,
                                                fontWeight: FontWeight.w500,
                                                color: Color(0xFF1A1A1A),
                                              ),
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Text(
                                      '${worstMargin.toStringAsFixed(1)}%',
                                      style: const TextStyle(
                                        fontSize: 13,
                                        fontWeight: FontWeight.w600,
                                        color: Color(0xFFFF4757),
                                      ),
                                    ),
                                  ],
                                ),
                              ],
                            ),
                            ),
                          )
                        else
                          GestureDetector(
                            onTap: () async {
                              await showStocksnapProUpgradeSheet(context);
                            },
                            child: Container(
                              width: double.infinity,
                              padding: const EdgeInsets.all(16),
                              decoration: BoxDecoration(
                                color: Colors.white,
                                borderRadius: BorderRadius.circular(16),
                                border: Border.all(
                                  color: const Color(0xFFE4E6EA),
                                ),
                              ),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Row(
                                    mainAxisAlignment:
                                        MainAxisAlignment.spaceBetween,
                                    children: [
                                      const Text(
                                        'MARGIN INSIGHTS',
                                        style: TextStyle(
                                          fontSize: 11,
                                          fontWeight: FontWeight.w600,
                                          color: Color(0xFF8A8A8A),
                                          letterSpacing: 1.2,
                                        ),
                                      ),
                                      Container(
                                        padding: const EdgeInsets.symmetric(
                                          horizontal: 8,
                                          vertical: 3,
                                        ),
                                        decoration: BoxDecoration(
                                          color: const Color(0xFF00C48C)
                                              .withValues(alpha: 0.1),
                                          borderRadius:
                                              BorderRadius.circular(6),
                                        ),
                                        child: const Text(
                                          'PRO',
                                          style: TextStyle(
                                            fontSize: 11,
                                            fontWeight: FontWeight.w700,
                                            color: Color(0xFF00C48C),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                  const SizedBox(height: 12),
                                  Column(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [
                                      Text(
                                        '${avgMargin.toStringAsFixed(1)}%',
                                        style: const TextStyle(
                                          fontSize: 28,
                                          fontWeight: FontWeight.w700,
                                        ),
                                      ),
                                      const SizedBox(height: 4),
                                      const Text(
                                        'Avg Margin Across All Items',
                                        style: TextStyle(
                                          fontSize: 12,
                                          color: Color(0xFF8A8A8A),
                                        ),
                                      ),
                                      const SizedBox(height: 12),
                                      Row(
                                        mainAxisAlignment:
                                            MainAxisAlignment.spaceBetween,
                                        children: [
                                          Expanded(
                                            child: Row(
                                              children: [
                                                const Text(
                                                  'Best item',
                                                  style: TextStyle(
                                                    fontSize: 13,
                                                    color: Color(0xFF8A8A8A),
                                                  ),
                                                ),
                                                const SizedBox(width: 4),
                                                Flexible(
                                                  child: ImageFiltered(
                                                    imageFilter:
                                                        ImageFilter.blur(
                                                      sigmaX: 4,
                                                      sigmaY: 4,
                                                    ),
                                                    child: Text(
                                                      bestItem?.name ?? '',
                                                      style: const TextStyle(
                                                        fontSize: 13,
                                                        fontWeight:
                                                            FontWeight.w500,
                                                        color:
                                                            Color(0xFF1A1A1A),
                                                      ),
                                                      overflow:
                                                          TextOverflow.ellipsis,
                                                      maxLines: 1,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                          Text(
                                            '${bestMargin.toStringAsFixed(1)}%',
                                            style: const TextStyle(
                                              fontSize: 13,
                                              fontWeight: FontWeight.w600,
                                              color: Color(0xFF00C48C),
                                            ),
                                          ),
                                        ],
                                      ),
                                      const SizedBox(height: 6),
                                      Row(
                                        mainAxisAlignment:
                                            MainAxisAlignment.spaceBetween,
                                        children: [
                                          Expanded(
                                            child: Row(
                                              children: [
                                                const Text(
                                                  'Worst item',
                                                  style: TextStyle(
                                                    fontSize: 13,
                                                    color: Color(0xFF8A8A8A),
                                                  ),
                                                ),
                                                const SizedBox(width: 4),
                                                Flexible(
                                                  child: ImageFiltered(
                                                    imageFilter:
                                                        ImageFilter.blur(
                                                      sigmaX: 4,
                                                      sigmaY: 4,
                                                    ),
                                                    child: Text(
                                                      worstItem?.name ?? '',
                                                      style: const TextStyle(
                                                        fontSize: 13,
                                                        fontWeight:
                                                            FontWeight.w500,
                                                        color:
                                                            Color(0xFF1A1A1A),
                                                      ),
                                                      overflow:
                                                          TextOverflow.ellipsis,
                                                      maxLines: 1,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                          Text(
                                            '${worstMargin.toStringAsFixed(1)}%',
                                            style: const TextStyle(
                                              fontSize: 13,
                                              fontWeight: FontWeight.w600,
                                              color: Color(0xFFFF4757),
                                            ),
                                          ),
                                        ],
                                      ),
                                      const SizedBox(height: 12),
                                      const Row(
                                        mainAxisAlignment:
                                            MainAxisAlignment.center,
                                        children: [
                                          Icon(
                                            Icons.lock_outline_rounded,
                                            size: 14,
                                            color: Color(0xFF8A8A8A),
                                          ),
                                          SizedBox(width: 4),
                                          Text(
                                            'Tap to unlock full insights',
                                            style: TextStyle(
                                              fontSize: 12,
                                              color: Color(0xFF8A8A8A),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ),
                          ),
                      ],
                    ),
            ),
    );
  }

  Widget _summaryCard({
    required String label,
    required String? value,
    required String subtext,
    bool locked = false,
    VoidCallback? onTap,
  }) {
    final card = Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(color: const Color(0xFFE4E6EA)),
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label,
            style: const TextStyle(
              fontSize: 11,
              fontWeight: FontWeight.w600,
              color: Color(0xFF8A8A8A),
              letterSpacing: 1.2,
            ),
          ),
          const SizedBox(height: 8),
          if (locked)
            const Icon(Icons.lock_outline, size: 30, color: Color(0xFF999999))
          else
            Expanded(
              child: Align(
                alignment: Alignment.centerLeft,
                child: FittedBox(
                  fit: BoxFit.scaleDown,
                  alignment: Alignment.centerLeft,
                  child: Text(
                    value ?? '-',
                    style: const TextStyle(
                      fontSize: 32,
                      fontWeight: FontWeight.w700,
                      color: Color(0xFF0A0A0A),
                      height: 1.1,
                    ),
                  ),
                ),
              ),
            ),
          const Spacer(),
          Text(
            subtext,
            style: const TextStyle(
              fontSize: 13,
              color: Color(0xFF8A8A8A),
            ),
          ),
        ],
      ),
    );
    if (onTap == null) return card;
    return GestureDetector(
      onTap: onTap,
      behavior: HitTestBehavior.opaque,
      child: card,
    );
  }

  Widget _listCard({EdgeInsets? margin, required Widget child}) {
    return Container(
      margin: margin ?? const EdgeInsets.only(bottom: 10),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(color: const Color(0xFFE4E6EA)),
        borderRadius: BorderRadius.circular(16),
      ),
      child: child,
    );
  }

  Widget _stateCard({
    required IconData icon,
    required String title,
    required String message,
  }) {
    return _listCard(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            Icon(icon, color: const Color(0xFF0A0A0A), size: 28),
            const SizedBox(height: 10),
            Text(
              title,
              style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 16),
            ),
            const SizedBox(height: 6),
            Text(
              message,
              textAlign: TextAlign.center,
              style: const TextStyle(color: Color(0xFF888888)),
            ),
          ],
        ),
      ),
    );
  }

  static pw.Widget _summaryItem(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(
            fontSize: 9,
            color: PdfColors.grey600,
          ),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 13,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      ],
    );
  }

  static pw.Widget _cell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      child: pw.Text(text, style: const pw.TextStyle(fontSize: 8)),
    );
  }
}
